[project]
name = "algo-practice"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Colin", email = "colin.vandervoort.42@gmail.com"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
pytest = "pytest"
ruff-check = "ruff check"
ruff-format = "ruff format"
lc-new = "cookiecutter -o leetcode tools/cookiecutter-leetcode-problem"

[dependency-groups]
formatting = [
    "ruff>=0.9.6",
]
test = [
    "pytest>=8.3.4",
]
automation = [
    "cookiecutter>=2.6.0",
]
