= data structures and algorithms (DSA) practice

This repository tracks most of my practice code for DSA problems, alongside some other information that I've compiled while preparing for software engineer interviews.

A secondary use of the repository is for tracking some of my preferred tools and conventions for working with different programming languages.

== setup

Follow the instructions in each directory.

* link:./python/README.adoc[Python]
* link:./rust/README.adoc[Rust]

== Templating

Creating directories and files for solution code modules can be a repetitive task. To avoid this chore and standardize solution formats, there are a few options below for automatically generating code.

=== Boilerplate

There are link:https://github.com/gruntwork-io/boilerplate[Boilerplate]-based templates for generating Golang and Rust LeetCode problem solution skeletons.

The below scripts handle passing the appropriate output directories for this repository of solutions.

link:./python/tools/boilerplate_lc_go.py[boilerplate_lc_go.py]

link:./python/tools/boilerplate_lc_rust.py[boilerplate_lc_rust.py]

=== Cookiecutter

There is a link:https://cookiecutter.readthedocs.io/en/stable/[Cookiecutter]-based template for generating Python LeetCode problem solution skeletons, see the link:_tools/cookiecutter/lc_py/cookiecutter.json[config file].

This template should be used via the link:./python/tools/cookiecutter_lc_py.py[lc_new_py.py] script, which passes the parameters for the template and output locations to Cookiecutter.

== Whiteboard / diagramming tools

* link:https://www.canva.com/online-whiteboard/[Canva whiteboard]
** supports freehand drawing
* link:https://miro.com/online-whiteboard/[miro lite]
* link:https://app.diagrams.net/[Draw.io]
** does NOT support freehand drawing
* link:https://www.lucidchart.com/[Lucidchart]
** does NOT support freehand drawing
** free tier:
*** Up to three (3) editable charts
*** Up to 60 objects per document

== Miscellaneous

* link:https://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE_Reference_Guide.pdf[IEEE Reference Style Guide for Authors]
