= data structures and algorithms (DSA) practice

== setup

Follow the instructions in each directory.

* link:./python/README.adoc[Python]
* link:./rust/README.adoc[Rust]

== Templating

Creating directories and files for solution code modules can be a repetitive task. To avoid this chore and standardize solution formats, there are a few options below for automatically generating code.

=== Boilerplate

There are link:https://github.com/gruntwork-io/boilerplate[Boilerplate]-based templates for generating Golang and Rust LeetCode problem solution skeletons.

The below scripts handle passing the appropriate output directories for this repository of solutions.

link:./python/tools/boilerplate_lc_go.py[boilerplate_lc_go.py]

link:./python/tools/boilerplate_lc_rust.py[boilerplate_lc_rust.py]

=== Cookiecutter

There is a link:https://cookiecutter.readthedocs.io/en/stable/[Cookiecutter]-based template for generating Python LeetCode problem solution skeletons, see the link:_tools/cookiecutter/lc_py/cookiecutter.json[config file].

This template should be used via the link:./python/tools/cookiecutter_lc_py.py[lc_new_py.py] script, which passes the parameters for the template and output locations to Cookiecutter.
